export const FETCH_COUNTRIES = "FETCH_COUNTRIES";
export const SET_COUNTRIESSORT = "SET_COUNTRIESSORT";
export const FETCH_COUNTRIESSORT = "FETCH_COUNTRIESSORT";
export const FETCH_COUNTRIESBYID = "FETCH_COUNTRIESBYID";
export const ERROR = "ERROR";
export const RESET_ERRORS = "RESET_ERRORS";

export const SET_COUNTRIESFILTER = "SET_COUNTRIESFILTER"
//export const FETCH_COUNTRIESFILTERS = "FETCH_COUNTRIESFILTERS"

export const FILTER_BY_ACTIVITY = "FILTER_BY_ACTIVITY"
export const FETCH_ACTIVITY = "FETCH _ACTIVITY"


