export const FETCH_COUNTRIES = "FETCH_COUNTRIES";
export const SET_COUNTRIESSORT = "SET_COUNTRIESSORT";
export const FETCH_COUNTRIESSORT = "FETCH_COUNTRIESSORT";
export const FETCH_COUNTRIESBYID = "FETCH_COUNTRIESBYID";
export const ERROR = "ERROR";
export const RESET_ERRORS = "RESET_ERRORS";



